#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${KRAKEN_API_KEY:-}" || -z "${KRAKEN_API_SECRET:-}" ]]; then
  echo "Missing Kraken Spot credentials in env: set KRAKEN_API_KEY and KRAKEN_API_SECRET" >&2
  exit 2
fi
if [[ "${KRAKEN_API_KEY}" == " "* || "${KRAKEN_API_KEY}" == *" " ]]; then
  echo "KRAKEN_API_KEY has leading/trailing space" >&2
  exit 2
fi
if [[ "${KRAKEN_API_SECRET}" == " "* || "${KRAKEN_API_SECRET}" == *" " ]]; then
  echo "KRAKEN_API_SECRET has leading/trailing space" >&2
  exit 2
fi

export AUTONOMOUS_LIVE_POLL_SECONDS="${AUTONOMOUS_LIVE_POLL_SECONDS:-1}"
export AUTONOMOUS_USER_MIN_ORDER_QUOTE="${AUTONOMOUS_USER_MIN_ORDER_QUOTE:-1.0}"
export AUTONOMOUS_SPOT_SELL_PROFIT_LOCK_FATAL_BYPASS="${AUTONOMOUS_SPOT_SELL_PROFIT_LOCK_FATAL_BYPASS:-false}"
export AUTONOMOUS_MIN_TP_AFTER_COSTS="${AUTONOMOUS_MIN_TP_AFTER_COSTS:-1}"
export AUTONOMOUS_MIN_TAKE_PROFIT_PCT="${AUTONOMOUS_MIN_TAKE_PROFIT_PCT:-0.9}"
export AUTONOMOUS_NO_LOSS_SELL="${AUTONOMOUS_NO_LOSS_SELL:-1}"
export AUTONOMOUS_TP_ONLY_MODE="${AUTONOMOUS_TP_ONLY_MODE:-1}"
export AUTONOMOUS_MAX_ORDERS_PER_MIN="${AUTONOMOUS_MAX_ORDERS_PER_MIN:-1}"
export AUTONOMOUS_TRADE_COOLDOWN_S="${AUTONOMOUS_TRADE_COOLDOWN_S:-300}"
export AUTONOMOUS_REBALANCE_DEADZONE_FACTOR="${AUTONOMOUS_REBALANCE_DEADZONE_FACTOR:-0.02}"
export AUTONOMOUS_REBALANCE_DEADZONE_FLOOR="${AUTONOMOUS_REBALANCE_DEADZONE_FLOOR:-0.01}"
export AUTONOMOUS_GUARDS_MODE="${AUTONOMOUS_GUARDS_MODE:-strict}"
export AUTONOMOUS_WALK_FORWARD_ENFORCE="${AUTONOMOUS_WALK_FORWARD_ENFORCE:-false}"
export AUTONOMOUS_NESTED_WALK_FORWARD_ENFORCE="${AUTONOMOUS_NESTED_WALK_FORWARD_ENFORCE:-false}"
export AUTONOMOUS_FALLBACK_SYMBOLS="${AUTONOMOUS_FALLBACK_SYMBOLS:-XBTEUR,ETHEUR,SOLEUR,XBTUSD,ETHUSD,SOLUSD}"
export AUTONOMOUS_UNIVERSE_ALLOWLIST="${AUTONOMOUS_UNIVERSE_ALLOWLIST:-${AUTONOMOUS_FALLBACK_SYMBOLS}}"
export AUTONOMOUS_DYNAMIC_UNIVERSE="${AUTONOMOUS_DYNAMIC_UNIVERSE:-true}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_ALL="${AUTONOMOUS_DYNAMIC_UNIVERSE_ALL:-false}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_MAX="${AUTONOMOUS_DYNAMIC_UNIVERSE_MAX:-120}"
export AUTONOMOUS_KRAKEN_TRADE_ALL="${AUTONOMOUS_KRAKEN_TRADE_ALL:-false}"
export AUTONOMOUS_PORTFOLIO_OPTIMIZER="${AUTONOMOUS_PORTFOLIO_OPTIMIZER:-true}"
export AUTONOMOUS_PORTFOLIO_RESELECT_EVERY_STEPS="${AUTONOMOUS_PORTFOLIO_RESELECT_EVERY_STEPS:-2}"
export AUTONOMOUS_PORTFOLIO_SCAN_BATCH="${AUTONOMOUS_PORTFOLIO_SCAN_BATCH:-260}"
export AUTONOMOUS_PORTFOLIO_TURNOVER_PENALTY="${AUTONOMOUS_PORTFOLIO_TURNOVER_PENALTY:-0.30}"
export AUTONOMOUS_PORTFOLIO_CLUSTER_CAP="${AUTONOMOUS_PORTFOLIO_CLUSTER_CAP:-0.60}"
export AUTONOMOUS_CHALLENGER_ENABLED="${AUTONOMOUS_CHALLENGER_ENABLED:-true}"
export AUTONOMOUS_ADAPTIVE_SIZING_ENABLED="${AUTONOMOUS_ADAPTIVE_SIZING_ENABLED:-true}"
export AUTONOMOUS_MIN_NET_EDGE_BPS="${AUTONOMOUS_MIN_NET_EDGE_BPS:-0.6}"
export AUTONOMOUS_DYNAMIC_EDGE_SPREAD_WEIGHT="${AUTONOMOUS_DYNAMIC_EDGE_SPREAD_WEIGHT:-0.020}"
export AUTONOMOUS_DYNAMIC_EDGE_VOL_WEIGHT="${AUTONOMOUS_DYNAMIC_EDGE_VOL_WEIGHT:-0.008}"
export AUTONOMOUS_DYNAMIC_EDGE_THIN_ADD_BPS="${AUTONOMOUS_DYNAMIC_EDGE_THIN_ADD_BPS:-0.35}"
export AUTONOMOUS_DYNAMIC_EDGE_PANIC_ADD_BPS="${AUTONOMOUS_DYNAMIC_EDGE_PANIC_ADD_BPS:-0.55}"
export AUTONOMOUS_DYNAMIC_EDGE_MAX_BPS="${AUTONOMOUS_DYNAMIC_EDGE_MAX_BPS:-0}"
export AUTONOMOUS_MAX_COST_TO_ALPHA_RATIO="${AUTONOMOUS_MAX_COST_TO_ALPHA_RATIO:-1.25}"
export AUTONOMOUS_MAKER_TIMEOUT_S="${AUTONOMOUS_MAKER_TIMEOUT_S:-12}"
export AUTONOMOUS_EXIT_TIME_STOP_S="${AUTONOMOUS_EXIT_TIME_STOP_S:-1800}"
export AUTONOMOUS_EXIT_TRAILING_DD_QUOTE="${AUTONOMOUS_EXIT_TRAILING_DD_QUOTE:-0.75}"
export AUTONOMOUS_EXIT_PARTIAL_FRACTION="${AUTONOMOUS_EXIT_PARTIAL_FRACTION:-0.5}"
export AUTONOMOUS_FEED_STALE_AFTER_S="${AUTONOMOUS_FEED_STALE_AFTER_S:-3.5}"
export AUTONOMOUS_MAX_CLOCK_DRIFT_MS="${AUTONOMOUS_MAX_CLOCK_DRIFT_MS:-500}"
export AUTONOMOUS_MIN_PRIMARY_FEED_SCORE="${AUTONOMOUS_MIN_PRIMARY_FEED_SCORE:-25}"
export AUTONOMOUS_RESERVE_CASH_RATIO="${AUTONOMOUS_RESERVE_CASH_RATIO:-0.12}"
export AUTONOMOUS_MIN_MARGIN_BUFFER_POLICY="${AUTONOMOUS_MIN_MARGIN_BUFFER_POLICY:-1.4}"
export AUTONOMOUS_ENFORCE_MANDATE="${AUTONOMOUS_ENFORCE_MANDATE:-true}"
export AUTONOMOUS_MANDATE_MAX_LEVERAGE="${AUTONOMOUS_MANDATE_MAX_LEVERAGE:-1}"
export AUTONOMOUS_BUS_MAX_ATTEMPTS="${AUTONOMOUS_BUS_MAX_ATTEMPTS:-3}"
export AUTONOMOUS_MODEL_STACK_V2="${AUTONOMOUS_MODEL_STACK_V2:-true}"
export AUTONOMOUS_KRAKEN_TICKER_TTL_S="${AUTONOMOUS_KRAKEN_TICKER_TTL_S:-1.0}"
export AUTONOMOUS_KRAKEN_BALANCE_TTL_S="${AUTONOMOUS_KRAKEN_BALANCE_TTL_S:-4.0}"
export AUTONOMOUS_KRAKEN_TRADES_TTL_S="${AUTONOMOUS_KRAKEN_TRADES_TTL_S:-3.0}"
export AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S="${AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S:-3.0}"
export AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S:-3.0}"
export AUTONOMOUS_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_RATE_LIMIT_COOLDOWN_S:-${AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S:-4.0}}"
export AUTONOMOUS_KRAKEN_RATE_LIMIT_STORM="${AUTONOMOUS_KRAKEN_RATE_LIMIT_STORM:-12}"
export AUTONOMOUS_KRAKEN_EXEC_RETRY_ATTEMPTS="${AUTONOMOUS_KRAKEN_EXEC_RETRY_ATTEMPTS:-4}"
export AUTONOMOUS_JURISDICTION="${AUTONOMOUS_JURISDICTION:-SK}"
export AUTONOMOUS_MIN_ORDER_NOTIONAL_QUOTE="${AUTONOMOUS_MIN_ORDER_NOTIONAL_QUOTE:-1.0}"
export ORDER_SUBMISSION_INTERVAL_SECONDS="${ORDER_SUBMISSION_INTERVAL_SECONDS:-300}"
export AUTONOMOUS_PROFIT_TARGET_NET="${AUTONOMOUS_PROFIT_TARGET_NET:-0.02}"
export AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS:-90}"
export AUTONOMOUS_SPOT_SELL_HARD_FLOOR_BPS="${AUTONOMOUS_SPOT_SELL_HARD_FLOOR_BPS:-90}"
export AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS:-90}"
export AUTONOMOUS_SPOT_SELL_TARGET_HOLD_S="${AUTONOMOUS_SPOT_SELL_TARGET_HOLD_S:-90}"
export AUTONOMOUS_MIN_SECONDS_BETWEEN_ORDERS="${AUTONOMOUS_MIN_SECONDS_BETWEEN_ORDERS:-300}"
export AUTONOMOUS_SELF_TUNER_ENABLED="${AUTONOMOUS_SELF_TUNER_ENABLED:-true}"
export AUTONOMOUS_SELF_TUNER_EVERY_STEPS="${AUTONOMOUS_SELF_TUNER_EVERY_STEPS:-5}"
export AUTONOMOUS_SELF_TUNER_WINDOW_EVENTS="${AUTONOMOUS_SELF_TUNER_WINDOW_EVENTS:-300}"
export AUTONOMOUS_SELF_TUNER_MIN_SAMPLES="${AUTONOMOUS_SELF_TUNER_MIN_SAMPLES:-10}"
export AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MIN="${AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MIN:-0.35}"
export AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MAX="${AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MAX:-1.75}"
export AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MIN="${AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MIN:-1}"
export AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MAX="${AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MAX:-10}"
export PYTHONUNBUFFERED=1
# Normalize config path because user shells sometimes export it with extra spaces.
LIVE_CONFIG="$(printf '%s' "${AUTONOMOUS_LIVE_CONFIG:-config.kraken_spot.live_profit.yaml}" | awk '{$1=$1};1')"
if [[ ! -f "${LIVE_CONFIG}" ]]; then
  LIVE_CONFIG="config.kraken_spot.live.yaml"
fi
RUN_DIR="${AUTONOMOUS_RUN_DIR:-}"
if [[ -z "${RUN_DIR}" ]]; then
  RUN_DIR="$(python3 - "${LIVE_CONFIG}" <<'PY'
from pathlib import Path
import json
import sys

config_path = Path(sys.argv[1])
default_run_dir = "runs/kraken_spot_live"
if not config_path.exists():
    print(default_run_dir)
    raise SystemExit(0)
text = config_path.read_text(encoding="utf-8")
data = {}
try:
    import yaml  # type: ignore

    parsed = yaml.safe_load(text)
    if isinstance(parsed, dict):
        data = parsed
except Exception:
    pass
if not data:
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            data = parsed
    except Exception:
        data = {}
storage = data.get("storage", {}) if isinstance(data, dict) else {}
run_dir = storage.get("run_dir") if isinstance(storage, dict) else None
if isinstance(run_dir, str) and run_dir.strip():
    print(run_dir.strip())
else:
    print(default_run_dir)
PY
)"
fi
for f in "${RUN_DIR}/env_overrides.sh" "${RUN_DIR}/operator_overrides.sh"; do
  if [[ -f "${f}" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "${f}"
    set +a
  fi
done

PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" && -x ".venv/bin/python" ]]; then
  PYTHON_BIN=".venv/bin/python"
fi
if [[ -z "${PYTHON_BIN}" ]]; then
  PYTHON_BIN="python3"
fi

# Prevent duplicate live runners for the same config/run directory.
if pgrep -f "python.*-m cli.run --config ${LIVE_CONFIG} --nonstop" >/dev/null 2>&1; then
  echo "[run_kraken_spot_live] Runner already active for ${LIVE_CONFIG}; skipping duplicate launch."
  exit 0
fi

FALLBACK_TO_PAPER_ON_PERM_DENIED="$(printf '%s' "${AUTONOMOUS_FALLBACK_TO_PAPER_ON_PERMISSION_DENIED:-true}" | tr '[:upper:]' '[:lower:]')"
PERM_CHECK_RESULT="$(
  PYTHONPATH=src "${PYTHON_BIN}" - <<'PY'
from autonomous_investment_robot.config.settings import KrakenSpotExecutionSettings
from autonomous_investment_robot.connectors.cex.kraken_spot import KrakenSpotConnector

settings = KrakenSpotExecutionSettings(allow_unknown_permissions=True)
connector = KrakenSpotConnector(settings)
checks = [
    ("balance", connector.balance),
    ("open_orders", connector.open_orders),
]
for name, fn in checks:
    try:
        fn()
    except Exception as exc:
        txt = str(exc).lower()
        if "permission denied" in txt or "invalid key" in txt or "invalid signature" in txt or "authentication" in txt:
            print(f"DENIED:{name}:{exc}")
            raise SystemExit(2)
print("OK")
PY
)" || true

if [[ "${PERM_CHECK_RESULT}" == DENIED:* ]]; then
  echo "[run_kraken_spot_live] Kraken private API permissions missing (${PERM_CHECK_RESULT})." >&2
  if [[ "${FALLBACK_TO_PAPER_ON_PERM_DENIED}" == "true" || "${FALLBACK_TO_PAPER_ON_PERM_DENIED}" == "1" || "${FALLBACK_TO_PAPER_ON_PERM_DENIED}" == "yes" || "${FALLBACK_TO_PAPER_ON_PERM_DENIED}" == "on" ]]; then
    echo "[run_kraken_spot_live] Switching to paper mode to avoid live error loops." >&2
    TESTNET_VALIDATED=true ENABLE_LIVE_TRADING=false ACK_I_UNDERSTAND_RISKS=true \
    PYTHONPATH=src "${PYTHON_BIN}" -m cli.run --config "${LIVE_CONFIG}" --paper --nonstop
    exit $?
  fi
  exit 3
fi

TESTNET_VALIDATED=true ENABLE_LIVE_TRADING=true ACK_I_UNDERSTAND_RISKS=true \
PYTHONPATH=src "${PYTHON_BIN}" -m cli.run --config "${LIVE_CONFIG}" --nonstop
