#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -z "${KRAKEN_API_KEY:-}" || -z "${KRAKEN_API_SECRET:-}" ]]; then
  echo "Missing Kraken Spot credentials in env: set KRAKEN_API_KEY and KRAKEN_API_SECRET" >&2
  exit 2
fi
if [[ "${KRAKEN_API_KEY}" == " "* || "${KRAKEN_API_KEY}" == *" " ]]; then
  echo "KRAKEN_API_KEY has leading/trailing space" >&2
  exit 2
fi
if [[ "${KRAKEN_API_SECRET}" == " "* || "${KRAKEN_API_SECRET}" == *" " ]]; then
  echo "KRAKEN_API_SECRET has leading/trailing space" >&2
  exit 2
fi

# Conservative defaults; operator can still override from shell or env_overrides.sh.
export AUTONOMOUS_LIVE_CONFIG="${AUTONOMOUS_LIVE_CONFIG:-config.kraken_spot.live_profit.yaml}"
export AUTONOMOUS_ENTRY_SAFE_MODE="${AUTONOMOUS_ENTRY_SAFE_MODE:-0}"
export AUTONOMOUS_GUARDS_MODE="${AUTONOMOUS_GUARDS_MODE:-strict}"
export AUTONOMOUS_GROWTH_MAX_FRACTION="${AUTONOMOUS_GROWTH_MAX_FRACTION:-0.30}"
export AUTONOMOUS_MANAGER_MAX_RUNTIME_S="${AUTONOMOUS_MANAGER_MAX_RUNTIME_S:-315360000}"
export AUTONOMOUS_MIN_NET_EDGE_BPS="${AUTONOMOUS_MIN_NET_EDGE_BPS:-0.7}"
export AUTONOMOUS_MAX_COST_TO_ALPHA_RATIO="${AUTONOMOUS_MAX_COST_TO_ALPHA_RATIO:-1.8}"
export AUTONOMOUS_VOLSTOP_THROTTLE_SCALE="${AUTONOMOUS_VOLSTOP_THROTTLE_SCALE:-0.30}"
export AUTONOMOUS_VOLSTOP_COOLDOWN_S="${AUTONOMOUS_VOLSTOP_COOLDOWN_S:-30}"
export AUTONOMOUS_MAX_ORDERS_PER_MIN="${AUTONOMOUS_MAX_ORDERS_PER_MIN:-8}"
export AUTONOMOUS_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_RATE_LIMIT_COOLDOWN_S:-3}"
export AUTONOMOUS_KRAKEN_TAKER_FALLBACK="${AUTONOMOUS_KRAKEN_TAKER_FALLBACK:-false}"
export AUTONOMOUS_KRAKEN_TAKER_FALLBACK_BUY="${AUTONOMOUS_KRAKEN_TAKER_FALLBACK_BUY:-false}"
export AUTONOMOUS_KRAKEN_TAKER_FALLBACK_SELL="${AUTONOMOUS_KRAKEN_TAKER_FALLBACK_SELL:-false}"
export AUTONOMOUS_EXIT_PROFIT_ONLY="${AUTONOMOUS_EXIT_PROFIT_ONLY:-true}"
export AUTONOMOUS_EXIT_MIN_PROFIT_QUOTE="${AUTONOMOUS_EXIT_MIN_PROFIT_QUOTE:-0.05}"
export AUTONOMOUS_EXIT_TAKE_PROFIT_PCT="${AUTONOMOUS_EXIT_TAKE_PROFIT_PCT:-5}"
export AUTONOMOUS_EXIT_TAKE_PROFIT_FULL_CLOSE="${AUTONOMOUS_EXIT_TAKE_PROFIT_FULL_CLOSE:-true}"
export AUTONOMOUS_EXIT_TIME_STOP_S="${AUTONOMOUS_EXIT_TIME_STOP_S:-315360000}"
export AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS:-200}"
export AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS:-500}"
export AUTONOMOUS_SPOT_SELL_TARGET_HOLD_S="${AUTONOMOUS_SPOT_SELL_TARGET_HOLD_S:-90}"
export AUTONOMOUS_SPOT_SELL_PROFIT_LOCK_FATAL_BYPASS="${AUTONOMOUS_SPOT_SELL_PROFIT_LOCK_FATAL_BYPASS:-false}"
export AUTONOMOUS_SPOT_SELL_REQUIRE_COST_BASIS="${AUTONOMOUS_SPOT_SELL_REQUIRE_COST_BASIS:-true}"
export AUTONOMOUS_MIN_SECONDS_BETWEEN_ORDERS="${AUTONOMOUS_MIN_SECONDS_BETWEEN_ORDERS:-30}"
export AUTONOMOUS_FALLBACK_CONSECUTIVE_REJECTS="${AUTONOMOUS_FALLBACK_CONSECUTIVE_REJECTS:-1000000}"
export AUTONOMOUS_NO_FILL_MIN_INTENTS="${AUTONOMOUS_NO_FILL_MIN_INTENTS:-1000000000}"
export AUTONOMOUS_TRADES_HISTORY_LOOKBACK_S="${AUTONOMOUS_TRADES_HISTORY_LOOKBACK_S:-86400}"
export AUTONOMOUS_SELL_BALANCE_BUFFER="${AUTONOMOUS_SELL_BALANCE_BUFFER:-0.985}"
export AUTONOMOUS_QUALITY_MAX_EDGE_CAP_BPS="${AUTONOMOUS_QUALITY_MAX_EDGE_CAP_BPS:-2.5}"
export AUTONOMOUS_FALLBACK_SYMBOLS="${AUTONOMOUS_FALLBACK_SYMBOLS:-XBTEUR,ETHEUR,SOLEUR,XBTUSD,ETHUSD,SOLUSD}"
export AUTONOMOUS_UNIVERSE_ALLOWLIST="${AUTONOMOUS_UNIVERSE_ALLOWLIST:-${AUTONOMOUS_FALLBACK_SYMBOLS}}"
export AUTONOMOUS_DYNAMIC_UNIVERSE="${AUTONOMOUS_DYNAMIC_UNIVERSE:-true}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_ALL="${AUTONOMOUS_DYNAMIC_UNIVERSE_ALL:-false}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_MAX="${AUTONOMOUS_DYNAMIC_UNIVERSE_MAX:-120}"
export AUTONOMOUS_KRAKEN_TRADE_ALL="${AUTONOMOUS_KRAKEN_TRADE_ALL:-false}"

export PYTHONPATH="${PYTHONPATH:-src}"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" && -x ".venv/bin/python" ]]; then
  PYTHON_BIN=".venv/bin/python"
fi
if [[ -z "${PYTHON_BIN}" ]]; then
  PYTHON_BIN="python3"
fi
exec "${PYTHON_BIN}" scripts/growth_manager.py
