#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_SCRIPT="${ROOT_DIR}/scripts/run_kraken_spot_profit_full_throttle.sh"
if [[ ! -x "${BASE_SCRIPT}" ]]; then
  echo "[run_kraken_ultra_profit_full_throttle] Missing base script: ${BASE_SCRIPT}" >&2
  exit 2
fi

export AUTONOMOUS_PROFILE="${AUTONOMOUS_PROFILE:-ultra_profit_full_throttle}"
export AUTONOMOUS_RUN_PROFILE="${AUTONOMOUS_RUN_PROFILE:-ULTRA_PROFIT_FULL_THROTTLE}"
export AUTONOMOUS_RUN_DIR="${AUTONOMOUS_RUN_DIR:-runs/kraken_ultra_profit_full_throttle}"

_mode_normalized="$(printf '%s' "${MODE:-${AUTONOMOUS_MODE:-}}" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]_-' '_')"
if [[ "${_mode_normalized}" == "eleven_out_of_ten_mode" || "${_mode_normalized}" == "eleven_out_of_ten" || "${_mode_normalized}" == "11_10" ]]; then
  export AUTONOMOUS_PROFILE="eleven_out_of_ten_mode"
  export AUTONOMOUS_RUN_PROFILE="ELEVEN_OUT_OF_TEN_MODE"
  export AUTONOMOUS_RUN_DIR="${AUTONOMOUS_RUN_DIR:-runs/kraken_eleven_out_of_ten_mode}"
fi
export AUTONOMOUS_REQUIRE_OPERATOR_LIVE_CONFIRMATION="${AUTONOMOUS_REQUIRE_OPERATOR_LIVE_CONFIRMATION:-1}"
export AUTONOMOUS_LIVE_GO="${AUTONOMOUS_LIVE_GO:-0}"
export AUTONOMOUS_LIVE_OPERATOR_CONFIRMATION_FILE="${AUTONOMOUS_LIVE_OPERATOR_CONFIRMATION_FILE:-ops/live_operator_confirmation.txt}"
export AUTONOMOUS_NODE_ROLE="${AUTONOMOUS_NODE_ROLE:-live}"
export AUTONOMOUS_DISTRIBUTED_ENABLED="${AUTONOMOUS_DISTRIBUTED_ENABLED:-1}"
export AUTONOMOUS_COMPUTE_BRIDGE="${AUTONOMOUS_COMPUTE_BRIDGE:-auto}"
export AUTONOMOUS_COMPUTE_TASK_TIMEOUT_S="${AUTONOMOUS_COMPUTE_TASK_TIMEOUT_S:-0.8}"
export AUTONOMOUS_COMPUTE_REFRESH_S="${AUTONOMOUS_COMPUTE_REFRESH_S:-10}"
export AUTONOMOUS_COMPUTE_TOP_N="${AUTONOMOUS_COMPUTE_TOP_N:-24}"
export AUTONOMOUS_STREAM_PREFIX="${AUTONOMOUS_STREAM_PREFIX:-autobot}"
export AUTONOMOUS_STREAM_PAYLOAD_VERSION="${AUTONOMOUS_STREAM_PAYLOAD_VERSION:-v1}"
if [[ -z "${AUTONOMOUS_REDIS_URL:-}" && -n "${REDIS_URL:-}" ]]; then
  export AUTONOMOUS_REDIS_URL="${REDIS_URL}"
fi
export AUTONOMOUS_POSTGRES_MIRROR_ENABLED="${AUTONOMOUS_POSTGRES_MIRROR_ENABLED:-0}"
if [[ -z "${AUTONOMOUS_POSTGRES_DSN:-}" && -n "${POSTGRES_DSN:-}" ]]; then
  export AUTONOMOUS_POSTGRES_DSN="${POSTGRES_DSN}"
fi
export AUTONOMOUS_DISABLE_ADVISORY_ON_LIVE_NODE="${AUTONOMOUS_DISABLE_ADVISORY_ON_LIVE_NODE:-1}"

# Explicit ultra throughput multiplier. Default is 5x for this profile.
_ultra_thr_raw="${AUTONOMOUS_THROUGHPUT_MULTIPLIER:-5}"
_ultra_thr="$(LC_ALL=C awk -v m="${_ultra_thr_raw}" 'BEGIN { x=(m+0); if (x < 1.0) x = 1.0; if (x > 8.0) x = 8.0; printf "%.6g", x }')"
export AUTONOMOUS_THROUGHPUT_MULTIPLIER="${_ultra_thr}"
export AUTONOMOUS_APPLY_THROUGHPUT_MULTIPLIER="${AUTONOMOUS_APPLY_THROUGHPUT_MULTIPLIER:-1}"

# Safe throughput midpoint tuning.
export AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S="${AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S:-120}"
export AUTONOMOUS_KRAKEN_BALANCE_TTL_S="${AUTONOMOUS_KRAKEN_BALANCE_TTL_S:-60}"
export AUTONOMOUS_KRAKEN_TRADES_TTL_S="${AUTONOMOUS_KRAKEN_TRADES_TTL_S:-90}"
export AUTONOMOUS_TRADES_HISTORY_SINCE_TS="${AUTONOMOUS_TRADES_HISTORY_SINCE_TS:-0}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD="${AUTONOMOUS_CONFIDENCE_THRESHOLD:-0.30}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD_CRYPTO="${AUTONOMOUS_CONFIDENCE_THRESHOLD_CRYPTO:-0.24}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD_XSTOCK="${AUTONOMOUS_CONFIDENCE_THRESHOLD_XSTOCK:-0.58}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD_XSTOCK_ETF="${AUTONOMOUS_CONFIDENCE_THRESHOLD_XSTOCK_ETF:-0.60}"
export AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_CRYPTO="${AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_CRYPTO:-92}"
export AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_XSTOCK="${AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_XSTOCK:-74}"
export AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_XSTOCK_ETF="${AUTONOMOUS_UNCERTAINTY_THRESHOLD_BPS_XSTOCK_ETF:-68}"
export AUTONOMOUS_RISK_PER_TRADE="${AUTONOMOUS_RISK_PER_TRADE:-0.0025}"
export AUTONOMOUS_MAX_PORTFOLIO_HEAT_RATIO="${AUTONOMOUS_MAX_PORTFOLIO_HEAT_RATIO:-0.0125}"
export AUTONOMOUS_MAX_SYMBOL_EXPOSURE_RATIO="${AUTONOMOUS_MAX_SYMBOL_EXPOSURE_RATIO:-0.0075}"
export AUTONOMOUS_RISK_STOP_PCT="${AUTONOMOUS_RISK_STOP_PCT:-0.0025}"
export AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S="${AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S:-3}"
export AUTONOMOUS_MAX_ORDERS_PER_MIN="${AUTONOMOUS_MAX_ORDERS_PER_MIN:-60}"
export AUTONOMOUS_MAX_PUBLIC_CALLS_PER_MIN="${AUTONOMOUS_MAX_PUBLIC_CALLS_PER_MIN:-120}"
export AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S:-8.0}"
export AUTONOMOUS_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_RATE_LIMIT_COOLDOWN_S:-8.0}"
export AUTONOMOUS_KRAKEN_TEMP_LOCKOUT_COOLDOWN_S="${AUTONOMOUS_KRAKEN_TEMP_LOCKOUT_COOLDOWN_S:-180.0}"
export AUTONOMOUS_MAX_CONSEC_REJECTS="${AUTONOMOUS_MAX_CONSEC_REJECTS:-12}"
export AUTONOMOUS_REJECT_COOLDOWN_S="${AUTONOMOUS_REJECT_COOLDOWN_S:-8}"
export AUTONOMOUS_MAX_ORDER_NOTIONAL_QUOTE="${AUTONOMOUS_MAX_ORDER_NOTIONAL_QUOTE:-2.00}"
export AUTONOMOUS_MAX_ORDER_NOTIONAL_QUOTE_DEFAULT="${AUTONOMOUS_MAX_ORDER_NOTIONAL_QUOTE_DEFAULT:-2.00}"
export AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS="${AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS:-1.5}"
export AUTONOMOUS_LIQUIDITY_NIGHT_SIZE_SCALE="${AUTONOMOUS_LIQUIDITY_NIGHT_SIZE_SCALE:-1.0}"
export AUTONOMOUS_LIQUIDITY_NIGHT_MAX_CHILD_ORDERS="${AUTONOMOUS_LIQUIDITY_NIGHT_MAX_CHILD_ORDERS:-3}"
export AUTONOMOUS_ORDER_CADENCE_S="${AUTONOMOUS_ORDER_CADENCE_S:-9}"
export AUTONOMOUS_DECISION_PER_SYMBOL="${AUTONOMOUS_DECISION_PER_SYMBOL:-1}"
export AUTONOMOUS_EXTRA_SUBMISSIONS_ENABLED="${AUTONOMOUS_EXTRA_SUBMISSIONS_ENABLED:-true}"
export AUTONOMOUS_EXTRA_SUBMISSIONS_MAX_PER_MIN="${AUTONOMOUS_EXTRA_SUBMISSIONS_MAX_PER_MIN:-12}"
export AUTONOMOUS_NO_TRADE_ZONE_REQUIRE_DEPTH="${AUTONOMOUS_NO_TRADE_ZONE_REQUIRE_DEPTH:-false}"
export AUTONOMOUS_EXPECTED_FILL_REQUIRE_DEPTH="${AUTONOMOUS_EXPECTED_FILL_REQUIRE_DEPTH:-false}"
export AUTONOMOUS_MICROSTRUCTURE_REQUIRE_DEPTH="${AUTONOMOUS_MICROSTRUCTURE_REQUIRE_DEPTH:-false}"
export AUTONOMOUS_QUOTE_RESERVE_RATIO="${AUTONOMOUS_QUOTE_RESERVE_RATIO:-1.00}"
export AUTONOMOUS_PROBE_QUOTE_RESERVE_RATIO="${AUTONOMOUS_PROBE_QUOTE_RESERVE_RATIO:-1.00}"
export AUTONOMOUS_PORTFOLIO_QUOTE_RESERVE_RATIO="${AUTONOMOUS_PORTFOLIO_QUOTE_RESERVE_RATIO:-1.00}"
export AUTONOMOUS_PORTFOLIO_AFFORDABILITY_BUFFER="${AUTONOMOUS_PORTFOLIO_AFFORDABILITY_BUFFER:-1.0}"
export AUTONOMOUS_QUOTE_MIN_BUFFER_MULT="${AUTONOMOUS_QUOTE_MIN_BUFFER_MULT:-1.0}"
export AUTONOMOUS_PROBE_QUOTE_MIN_BUFFER_MULT="${AUTONOMOUS_PROBE_QUOTE_MIN_BUFFER_MULT:-1.0}"
export AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE="${AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE:-120.0}"
export AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_BTC="${AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_BTC:-0.02}"
export AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_ETH="${AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_ETH:-0.25}"
export AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_OTHER_CRYPTO="${AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_OTHER_CRYPTO:-5.0}"
export AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_XSTOCK="${AUTONOMOUS_BOOK_MIN_DEPTH_QUOTE_XSTOCK:-120.0}"
export AUTONOMOUS_SELL_HARD_MIN_PROFIT_BPS="${AUTONOMOUS_SELL_HARD_MIN_PROFIT_BPS:-33}"
export AUTONOMOUS_SELL_MIN_NET_PROFIT_BPS="${AUTONOMOUS_SELL_MIN_NET_PROFIT_BPS:-33}"
export AUTONOMOUS_SPOT_SELL_HARD_FLOOR_BPS="${AUTONOMOUS_SPOT_SELL_HARD_FLOOR_BPS:-33}"
export AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_MIN_PROFIT_BPS:-33}"
export AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS="${AUTONOMOUS_SPOT_SELL_TARGET_PROFIT_BPS:-33}"
export AUTONOMOUS_PROFIT_TARGET_NET="${AUTONOMOUS_PROFIT_TARGET_NET:-0.0033}"

# LLM advisory defaults: Groq primary, OpenAI-compatible.
export LLM_PROVIDER="${LLM_PROVIDER:-groq}"
export LLM_BASE_URL="${LLM_BASE_URL:-https://api.groq.com/openai/v1}"
export LLM_MODEL_PRIMARY="${LLM_MODEL_PRIMARY:-openai/gpt-oss-120b}"
export LLM_MODEL_FALLBACK="${LLM_MODEL_FALLBACK:-openai/gpt-oss-20b}"
export LLM_MODEL="${LLM_MODEL:-${LLM_MODEL_PRIMARY}}"
export LLM_ENABLED="${LLM_ENABLED:-1}"
export AUTONOMOUS_SELF_IMPROVEMENT_ENABLED="${AUTONOMOUS_SELF_IMPROVEMENT_ENABLED:-1}"
export AUTONOMOUS_SELF_IMPROVEMENT_LLM_ENABLED="${AUTONOMOUS_SELF_IMPROVEMENT_LLM_ENABLED:-1}"

# Forecast backend + bounded self-optimization.
export AUTONOMOUS_FORECAST_BACKEND="${AUTONOMOUS_FORECAST_BACKEND:-auto}"
export AUTONOMOUS_TRANSFORMER_BACKEND_ENABLED="${AUTONOMOUS_TRANSFORMER_BACKEND_ENABLED:-1}"
export AUTONOMOUS_FOUNDATION_BACKEND_ENABLED="${AUTONOMOUS_FOUNDATION_BACKEND_ENABLED:-1}"
export AUTONOMOUS_SELF_OPTIMIZATION_WINDOW="${AUTONOMOUS_SELF_OPTIMIZATION_WINDOW:-160}"
export AUTONOMOUS_SELF_OPTIMIZATION_MIN_SAMPLES="${AUTONOMOUS_SELF_OPTIMIZATION_MIN_SAMPLES:-28}"
export AUTONOMOUS_SELF_OPTIMIZATION_APPLY_EVERY="${AUTONOMOUS_SELF_OPTIMIZATION_APPLY_EVERY:-10}"
export AUTONOMOUS_SELF_TUNER_ENABLED="${AUTONOMOUS_SELF_TUNER_ENABLED:-1}"
export AUTONOMOUS_SELF_TUNER_SIZE_SCALE_INIT="${AUTONOMOUS_SELF_TUNER_SIZE_SCALE_INIT:-0.45}"
export AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MIN="${AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MIN:-0.30}"
export AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MAX="${AUTONOMOUS_SELF_TUNER_SIZE_SCALE_MAX:-1.00}"
export AUTONOMOUS_SELF_TUNER_EVERY_STEPS="${AUTONOMOUS_SELF_TUNER_EVERY_STEPS:-8}"
export AUTONOMOUS_SELF_TUNER_MIN_SAMPLES="${AUTONOMOUS_SELF_TUNER_MIN_SAMPLES:-12}"
export AUTONOMOUS_VALIDATION_WINDOW_TRADES="${AUTONOMOUS_VALIDATION_WINDOW_TRADES:-120}"
export AUTONOMOUS_VALIDATION_MAX_REJECT_RATE="${AUTONOMOUS_VALIDATION_MAX_REJECT_RATE:-0.60}"
export AUTONOMOUS_VALIDATION_COOLDOWN_S="${AUTONOMOUS_VALIDATION_COOLDOWN_S:-300}"
export AUTONOMOUS_SYMBOL_TOPK="${AUTONOMOUS_SYMBOL_TOPK:-120}"
export AUTONOMOUS_STORM_ENABLED="${AUTONOMOUS_STORM_ENABLED:-1}"
export AUTONOMOUS_STORM_TOP_N="${AUTONOMOUS_STORM_TOP_N:-48}"
export AUTONOMOUS_STORM_REGIME_MULT_TREND="${AUTONOMOUS_STORM_REGIME_MULT_TREND:-1.18}"
export AUTONOMOUS_STORM_REGIME_MULT_RANGE="${AUTONOMOUS_STORM_REGIME_MULT_RANGE:-0.92}"
export AUTONOMOUS_STORM_REGIME_MULT_CHOP="${AUTONOMOUS_STORM_REGIME_MULT_CHOP:-0.82}"
export AUTONOMOUS_STORM_REGIME_MULT_PANIC="${AUTONOMOUS_STORM_REGIME_MULT_PANIC:-0.45}"
export AUTONOMOUS_STORM_LIQUIDITY_MULT_GOOD="${AUTONOMOUS_STORM_LIQUIDITY_MULT_GOOD:-1.05}"
export AUTONOMOUS_STORM_LIQUIDITY_MULT_THIN="${AUTONOMOUS_STORM_LIQUIDITY_MULT_THIN:-0.60}"
export AUTONOMOUS_STORM_EXEC_QUALITY_FLOOR="${AUTONOMOUS_STORM_EXEC_QUALITY_FLOOR:-0.35}"
export AUTONOMOUS_STORM_EXEC_REJECT_TARGET="${AUTONOMOUS_STORM_EXEC_REJECT_TARGET:-0.25}"
export AUTONOMOUS_STORM_EXEC_FILL_TARGET="${AUTONOMOUS_STORM_EXEC_FILL_TARGET:-0.35}"
export AUTONOMOUS_REGIME_SIZE_MULT_BULL_TREND="${AUTONOMOUS_REGIME_SIZE_MULT_BULL_TREND:-1.15}"
export AUTONOMOUS_REGIME_SIZE_MULT_TREND="${AUTONOMOUS_REGIME_SIZE_MULT_TREND:-1.10}"
export AUTONOMOUS_REGIME_SIZE_MULT_RANGE="${AUTONOMOUS_REGIME_SIZE_MULT_RANGE:-0.95}"
export AUTONOMOUS_REGIME_SIZE_MULT_CHOP="${AUTONOMOUS_REGIME_SIZE_MULT_CHOP:-0.80}"
export AUTONOMOUS_REGIME_SIZE_MULT_PANIC="${AUTONOMOUS_REGIME_SIZE_MULT_PANIC:-0.45}"
export AUTONOMOUS_REGIME_SIZE_MULT_HIGH_VOL="${AUTONOMOUS_REGIME_SIZE_MULT_HIGH_VOL:-0.60}"
export AUTONOMOUS_REGIME_SIZE_MULT_LOW_LIQUIDITY="${AUTONOMOUS_REGIME_SIZE_MULT_LOW_LIQUIDITY:-0.55}"
export AUTONOMOUS_OPPORTUNITY_DECAY_MAX_AGE_S="${AUTONOMOUS_OPPORTUNITY_DECAY_MAX_AGE_S:-45}"
export AUTONOMOUS_OPPORTUNITY_DECAY_GUARD_THRESHOLD="${AUTONOMOUS_OPPORTUNITY_DECAY_GUARD_THRESHOLD:-0.65}"
export AUTONOMOUS_CROSS_MARKET_CONFIRMATION_ENABLED="${AUTONOMOUS_CROSS_MARKET_CONFIRMATION_ENABLED:-1}"
export AUTONOMOUS_CROSS_MARKET_CONFIRMATION_MIN="${AUTONOMOUS_CROSS_MARKET_CONFIRMATION_MIN:--0.35}"
export AUTONOMOUS_COUNTERFACTUAL_MIN_EDGE_BPS="${AUTONOMOUS_COUNTERFACTUAL_MIN_EDGE_BPS:-1.0}"
export AUTONOMOUS_MARKET_TWIN_INCLUDE_ADVANCED_SCENARIOS="${AUTONOMOUS_MARKET_TWIN_INCLUDE_ADVANCED_SCENARIOS:-1}"
export AUTONOMOUS_MARKET_TWIN_MAX_SNAPSHOTS="${AUTONOMOUS_MARKET_TWIN_MAX_SNAPSHOTS:-256}"
export AUTONOMOUS_POLICY_EDGE_SCALE="${AUTONOMOUS_POLICY_EDGE_SCALE:-4.8}"
export AUTONOMOUS_POLICY_FC_MU_WEIGHT="${AUTONOMOUS_POLICY_FC_MU_WEIGHT:-1.4}"
export AUTONOMOUS_POLICY_EDGE_HORIZON_SCALE="${AUTONOMOUS_POLICY_EDGE_HORIZON_SCALE:-1.8}"
export AUTONOMOUS_FEE_AWARE_EDGE_BUFFER_BPS="${AUTONOMOUS_FEE_AWARE_EDGE_BUFFER_BPS:-0.0}"
export AUTONOMOUS_FEE_AWARE_REQUIRE_SELL_FLOOR_FOR_ENTRY="${AUTONOMOUS_FEE_AWARE_REQUIRE_SELL_FLOOR_FOR_ENTRY:-false}"
export AUTONOMOUS_FEE_AWARE_ENTRY_MIN_EDGE_BPS="${AUTONOMOUS_FEE_AWARE_ENTRY_MIN_EDGE_BPS:-0.25}"
export AUTONOMOUS_DUST_FLOOR_UPSIZE_ENABLED="${AUTONOMOUS_DUST_FLOOR_UPSIZE_ENABLED:-true}"

# Market-class-aware universe support (safe defaults, can be overridden).
export AUTONOMOUS_ENABLE_CRYPTO_SPOT="${AUTONOMOUS_ENABLE_CRYPTO_SPOT:-true}"
export AUTONOMOUS_ENABLE_XSTOCKS="${AUTONOMOUS_ENABLE_XSTOCKS:-false}"
export AUTONOMOUS_ENABLE_XSTOCKS_ETF="${AUTONOMOUS_ENABLE_XSTOCKS_ETF:-false}"
export AUTONOMOUS_MIXED_UNIVERSE_MODE="${AUTONOMOUS_MIXED_UNIVERSE_MODE:-false}"
export AUTONOMOUS_XSTOCKS_SESSION_AWARE="${AUTONOMOUS_XSTOCKS_SESSION_AWARE:-true}"
export AUTONOMOUS_XSTOCKS_ALLOW_OFF_HOURS="${AUTONOMOUS_XSTOCKS_ALLOW_OFF_HOURS:-false}"
export AUTONOMOUS_UNIVERSE_MODE="${AUTONOMOUS_UNIVERSE_MODE:-kraken_spot_dynamic}"
export AUTONOMOUS_UNIVERSE_MAX_PAIRS="${AUTONOMOUS_UNIVERSE_MAX_PAIRS:-120}"
export AUTONOMOUS_DYNAMIC_UNIVERSE="${AUTONOMOUS_DYNAMIC_UNIVERSE:-true}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_ALL="${AUTONOMOUS_DYNAMIC_UNIVERSE_ALL:-true}"
export AUTONOMOUS_DYNAMIC_UNIVERSE_MAX="${AUTONOMOUS_DYNAMIC_UNIVERSE_MAX:-2000}"
export AUTONOMOUS_UNIVERSE_MIN_24H_VOL_QUOTE="${AUTONOMOUS_UNIVERSE_MIN_24H_VOL_QUOTE:-10000}"
export AUTONOMOUS_UNIVERSE_MAX_SPREAD_BPS="${AUTONOMOUS_UNIVERSE_MAX_SPREAD_BPS:-80}"
export AUTONOMOUS_PORTFOLIO_PREFILTER_MAX_SPREAD_BPS="${AUTONOMOUS_PORTFOLIO_PREFILTER_MAX_SPREAD_BPS:-80}"
_ultra_min_order_floor_quote="${AUTONOMOUS_ULTRA_MIN_ORDER_FLOOR_QUOTE:-0.25}"
_ultra_force_floor="$(printf '%s' "${AUTONOMOUS_ULTRA_FORCE_MIN_ORDER_FLOOR:-1}" | tr '[:upper:]' '[:lower:]')"
if [[ "${_ultra_force_floor}" == "1" || "${_ultra_force_floor}" == "true" || "${_ultra_force_floor}" == "yes" || "${_ultra_force_floor}" == "on" ]]; then
  export AUTONOMOUS_MIN_ORDER_HARD_FLOOR_QUOTE="${_ultra_min_order_floor_quote}"
  export AUTONOMOUS_USER_MIN_ORDER_QUOTE="${_ultra_min_order_floor_quote}"
  export AUTONOMOUS_EXCHANGE_MIN_ORDER_QUOTE_FALLBACK="${_ultra_min_order_floor_quote}"
else
  export AUTONOMOUS_MIN_ORDER_HARD_FLOOR_QUOTE="${AUTONOMOUS_MIN_ORDER_HARD_FLOOR_QUOTE:-${_ultra_min_order_floor_quote}}"
  export AUTONOMOUS_USER_MIN_ORDER_QUOTE="${AUTONOMOUS_USER_MIN_ORDER_QUOTE:-${_ultra_min_order_floor_quote}}"
  export AUTONOMOUS_EXCHANGE_MIN_ORDER_QUOTE_FALLBACK="${AUTONOMOUS_EXCHANGE_MIN_ORDER_QUOTE_FALLBACK:-${_ultra_min_order_floor_quote}}"
fi
export AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MIN="${AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MIN:-${_ultra_min_order_floor_quote}}"
export AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MAX="${AUTONOMOUS_SELF_TUNER_MIN_ORDER_FLOOR_MAX:-${_ultra_min_order_floor_quote}}"
export AUTONOMOUS_UNIVERSE_QUOTE_ALLOWLIST="${AUTONOMOUS_UNIVERSE_QUOTE_ALLOWLIST:-USD,USDT,EUR,USDC,XBT}"
export AUTONOMOUS_SMALL_BALANCE_MODE="${AUTONOMOUS_SMALL_BALANCE_MODE:-1}"
export AUTONOMOUS_SMALL_BALANCE_ALLOWLIST="${AUTONOMOUS_SMALL_BALANCE_ALLOWLIST:-}"
export AUTONOMOUS_FALLBACK_SYMBOLS="${AUTONOMOUS_FALLBACK_SYMBOLS:-}"
export AUTONOMOUS_PORTFOLIO_RESELECT_EVERY_STEPS="${AUTONOMOUS_PORTFOLIO_RESELECT_EVERY_STEPS:-1}"
export AUTONOMOUS_PORTFOLIO_SCAN_BATCH="${AUTONOMOUS_PORTFOLIO_SCAN_BATCH:-160}"
export AUTONOMOUS_PORTFOLIO_RESCUE_SCAN_LIMIT="${AUTONOMOUS_PORTFOLIO_RESCUE_SCAN_LIMIT:-800}"
export AUTONOMOUS_PORTFOLIO_PREFILTER_QUOTE_CHECK_LIMIT="${AUTONOMOUS_PORTFOLIO_PREFILTER_QUOTE_CHECK_LIMIT:-64}"
export AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S="${AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S:-3}"
export AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_RATIO_FLOOR="${AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_RATIO_FLOOR:-0.80}"
export AUTONOMOUS_SYMBOL_QUARANTINE_MIN="${AUTONOMOUS_SYMBOL_QUARANTINE_MIN:-3}"
export AUTONOMOUS_CAPITAL_UNLOCK_SELL_ENABLED="${AUTONOMOUS_CAPITAL_UNLOCK_SELL_ENABLED:-true}"
export AUTONOMOUS_CAPITAL_UNLOCK_SELL_COVER_RATIO="${AUTONOMOUS_CAPITAL_UNLOCK_SELL_COVER_RATIO:-1.10}"
export AUTONOMOUS_CAPITAL_UNLOCK_SELL_BYPASS_TP_TARGET="${AUTONOMOUS_CAPITAL_UNLOCK_SELL_BYPASS_TP_TARGET:-true}"

# Prefer actively-held assets for capital unlock and rebalance cycles.
# Operator can override via AUTONOMOUS_HOLDINGS_SELL_PRIORITY="".
export AUTONOMOUS_HOLDINGS_SELL_PRIORITY="${AUTONOMOUS_HOLDINGS_SELL_PRIORITY:-ATOMUSD,SOLUSD,ADAUSD,0GUSD,ATOMEUR,SOLEUR,ADAEUR,0GEUR,ATOMXBT,SOLXBT,ADAXBT}"
if [[ -n "${AUTONOMOUS_HOLDINGS_SELL_PRIORITY}" ]]; then
  export AUTONOMOUS_OPERATOR_UNIVERSE_OVERRIDE="${AUTONOMOUS_OPERATOR_UNIVERSE_OVERRIDE:-${AUTONOMOUS_HOLDINGS_SELL_PRIORITY}}"
  export AUTONOMOUS_FALLBACK_SYMBOLS="${AUTONOMOUS_FALLBACK_SYMBOLS:-${AUTONOMOUS_HOLDINGS_SELL_PRIORITY}}"
  export AUTONOMOUS_DYNAMIC_UNIVERSE="false"
  export AUTONOMOUS_DYNAMIC_UNIVERSE_ALL="false"
  export AUTONOMOUS_UNIVERSE_MODE="kraken_spot_manual"
fi

_ultra_apply_norm="$(printf '%s' "${AUTONOMOUS_APPLY_THROUGHPUT_MULTIPLIER:-1}" | tr '[:upper:]' '[:lower:]')"
if [[ "${_ultra_apply_norm}" == "1" || "${_ultra_apply_norm}" == "true" || "${_ultra_apply_norm}" == "yes" || "${_ultra_apply_norm}" == "on" ]]; then
  export AUTONOMOUS_ORDER_CADENCE_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_ORDER_CADENCE_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 3.0) x = 3.0; if (x > 60.0) x = 60.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_LIVE_POLL_SECONDS="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_LIVE_POLL_SECONDS:-1.0}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 0.2) x = 0.2; if (x > 2.0) x = 2.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_MAX_ORDERS_PER_MIN="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_MAX_ORDERS_PER_MIN}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 60) x = 60; if (x > 180) x = 180; printf "%d", x
    }'
  )"
  export AUTONOMOUS_MAX_PUBLIC_CALLS_PER_MIN="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_MAX_PUBLIC_CALLS_PER_MIN}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 240) x = 240; if (x > 720) x = 720; printf "%d", x
    }'
  )"
  export AUTONOMOUS_EXTRA_SUBMISSIONS_MAX_PER_MIN="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_EXTRA_SUBMISSIONS_MAX_PER_MIN}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 12) x = 12; if (x > 60) x = 60; printf "%d", x
    }'
  )"
  export AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 4.0) x = 4.0; if (x > 60.0) x = 60.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_KRAKEN_BALANCE_TTL_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_KRAKEN_BALANCE_TTL_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 2.0) x = 2.0; if (x > 30.0) x = 30.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_KRAKEN_TRADES_TTL_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_KRAKEN_TRADES_TTL_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 3.0) x = 3.0; if (x > 45.0) x = 45.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_INSUFFICIENT_BALANCE_COOLDOWN_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 1.0) x = 1.0; if (x > 8.0) x = 8.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_RATE_LIMIT_COOLDOWN_S="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_RATE_LIMIT_COOLDOWN_S}" -v m="${_ultra_thr}" 'BEGIN {
      x=(base+0)/m; if (x < 1.0) x = 1.0; if (x > 5.0) x = 5.0; printf "%.6g", x
    }'
  )"
  export AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S="${AUTONOMOUS_KRAKEN_RATE_LIMIT_COOLDOWN_S:-${AUTONOMOUS_RATE_LIMIT_COOLDOWN_S}}"
  export AUTONOMOUS_SYMBOL_TOPK="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_SYMBOL_TOPK}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 120) x = 120; if (x > 400) x = 400; printf "%d", x
    }'
  )"
  export AUTONOMOUS_STORM_TOP_N="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_STORM_TOP_N}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 48) x = 48; if (x > 160) x = 160; printf "%d", x
    }'
  )"
  export AUTONOMOUS_COMPUTE_TOP_N="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_COMPUTE_TOP_N}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 24) x = 24; if (x > 120) x = 120; printf "%d", x
    }'
  )"
  export AUTONOMOUS_PARALLEL_SYMBOL_WORKERS="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_PARALLEL_SYMBOL_WORKERS:-4}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 4) x = 4; if (x > 32) x = 32; printf "%d", x
    }'
  )"
  export AUTONOMOUS_PORTFOLIO_SCAN_BATCH="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_PORTFOLIO_SCAN_BATCH}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 96) x = 96; if (x > 320) x = 320; printf "%d", x
    }'
  )"
  export AUTONOMOUS_PORTFOLIO_RESCUE_SCAN_LIMIT="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_PORTFOLIO_RESCUE_SCAN_LIMIT}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 256) x = 256; if (x > 1024) x = 1024; printf "%d", x
    }'
  )"
  export AUTONOMOUS_PORTFOLIO_PREFILTER_QUOTE_CHECK_LIMIT="$(
    LC_ALL=C awk -v base="${AUTONOMOUS_PORTFOLIO_PREFILTER_QUOTE_CHECK_LIMIT}" -v m="${_ultra_thr}" 'BEGIN {
      x=int((base+0)*m + 0.5); if (x < 16) x = 16; if (x > 64) x = 64; printf "%d", x
    }'
  )"
fi
# In ultra mode default to dynamic market-scored universe; only use allowlist when explicitly provided.
if [[ -z "${AUTONOMOUS_UNIVERSE_ALLOWLIST+x}" ]]; then
  _small_balance_mode_norm="$(printf '%s' "${AUTONOMOUS_SMALL_BALANCE_MODE}" | tr '[:upper:]' '[:lower:]')"
  _small_balance_allowlist_trimmed="$(printf '%s' "${AUTONOMOUS_SMALL_BALANCE_ALLOWLIST}" | tr -d '[:space:]')"
  if [[ "${_small_balance_mode_norm}" == "1" || "${_small_balance_mode_norm}" == "true" || "${_small_balance_mode_norm}" == "yes" || "${_small_balance_mode_norm}" == "on" ]]; then
    if [[ -n "${_small_balance_allowlist_trimmed}" ]]; then
      export AUTONOMOUS_UNIVERSE_ALLOWLIST="${AUTONOMOUS_SMALL_BALANCE_ALLOWLIST}"
    else
      export AUTONOMOUS_UNIVERSE_ALLOWLIST=""
    fi
  else
    export AUTONOMOUS_UNIVERSE_ALLOWLIST=""
  fi
fi

exec "${BASE_SCRIPT}"
