#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_SCRIPT="${ROOT_DIR}/scripts/run_kraken_spot_profit_full_throttle.sh"
if [[ ! -x "${BASE_SCRIPT}" ]]; then
  echo "[run_kraken_ultra_profit_full_throttle] Missing base script: ${BASE_SCRIPT}" >&2
  exit 2
fi

export AUTONOMOUS_PROFILE="${AUTONOMOUS_PROFILE:-ultra_profit_full_throttle}"
export AUTONOMOUS_RUN_PROFILE="${AUTONOMOUS_RUN_PROFILE:-ULTRA_PROFIT_FULL_THROTTLE}"
export AUTONOMOUS_RUN_DIR="${AUTONOMOUS_RUN_DIR:-runs/kraken_ultra_profit_full_throttle}"

# Safe throughput midpoint tuning.
export AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S="${AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S:-60}"
export AUTONOMOUS_KRAKEN_BALANCE_TTL_S="${AUTONOMOUS_KRAKEN_BALANCE_TTL_S:-30}"
export AUTONOMOUS_KRAKEN_TRADES_TTL_S="${AUTONOMOUS_KRAKEN_TRADES_TTL_S:-45}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD="${AUTONOMOUS_CONFIDENCE_THRESHOLD:-0.44}"
export AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS="${AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS:-1.5}"
export AUTONOMOUS_ORDER_CADENCE_S="${AUTONOMOUS_ORDER_CADENCE_S:-9}"

# LLM advisory defaults: Groq primary, OpenAI-compatible.
export LLM_PROVIDER="${LLM_PROVIDER:-groq}"
export LLM_BASE_URL="${LLM_BASE_URL:-https://api.groq.com/openai/v1}"
export LLM_MODEL_PRIMARY="${LLM_MODEL_PRIMARY:-openai/gpt-oss-120b}"
export LLM_MODEL_FALLBACK="${LLM_MODEL_FALLBACK:-openai/gpt-oss-20b}"
export LLM_MODEL="${LLM_MODEL:-${LLM_MODEL_PRIMARY}}"
export LLM_ENABLED="${LLM_ENABLED:-1}"
export AUTONOMOUS_SELF_IMPROVEMENT_ENABLED="${AUTONOMOUS_SELF_IMPROVEMENT_ENABLED:-1}"
export AUTONOMOUS_SELF_IMPROVEMENT_LLM_ENABLED="${AUTONOMOUS_SELF_IMPROVEMENT_LLM_ENABLED:-1}"

# Forecast backend + bounded self-optimization.
export AUTONOMOUS_FORECAST_BACKEND="${AUTONOMOUS_FORECAST_BACKEND:-auto}"
export AUTONOMOUS_TRANSFORMER_BACKEND_ENABLED="${AUTONOMOUS_TRANSFORMER_BACKEND_ENABLED:-1}"
export AUTONOMOUS_FOUNDATION_BACKEND_ENABLED="${AUTONOMOUS_FOUNDATION_BACKEND_ENABLED:-1}"
export AUTONOMOUS_SELF_OPTIMIZATION_WINDOW="${AUTONOMOUS_SELF_OPTIMIZATION_WINDOW:-160}"
export AUTONOMOUS_SELF_OPTIMIZATION_MIN_SAMPLES="${AUTONOMOUS_SELF_OPTIMIZATION_MIN_SAMPLES:-28}"
export AUTONOMOUS_SELF_OPTIMIZATION_APPLY_EVERY="${AUTONOMOUS_SELF_OPTIMIZATION_APPLY_EVERY:-10}"

# Market-class-aware universe support (safe defaults, can be overridden).
export AUTONOMOUS_ENABLE_CRYPTO_SPOT="${AUTONOMOUS_ENABLE_CRYPTO_SPOT:-true}"
export AUTONOMOUS_ENABLE_XSTOCKS="${AUTONOMOUS_ENABLE_XSTOCKS:-true}"
export AUTONOMOUS_ENABLE_XSTOCKS_ETF="${AUTONOMOUS_ENABLE_XSTOCKS_ETF:-true}"
export AUTONOMOUS_MIXED_UNIVERSE_MODE="${AUTONOMOUS_MIXED_UNIVERSE_MODE:-true}"
export AUTONOMOUS_XSTOCKS_SESSION_AWARE="${AUTONOMOUS_XSTOCKS_SESSION_AWARE:-true}"
export AUTONOMOUS_XSTOCKS_ALLOW_OFF_HOURS="${AUTONOMOUS_XSTOCKS_ALLOW_OFF_HOURS:-false}"

exec "${BASE_SCRIPT}"
