#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ULTRA_SCRIPT="${ROOT_DIR}/scripts/run_kraken_ultra_profit_full_throttle.sh"
if [[ ! -x "${ULTRA_SCRIPT}" ]]; then
  echo "[start_eleven_out_of_ten_mode] Missing ultra launcher: ${ULTRA_SCRIPT}" >&2
  exit 2
fi

export MODE="${MODE:-ELEVEN_OUT_OF_TEN_MODE}"
export AUTONOMOUS_MODE="${AUTONOMOUS_MODE:-ELEVEN_OUT_OF_TEN_MODE}"
export AUTONOMOUS_PROFILE="${AUTONOMOUS_PROFILE:-eleven_out_of_ten_mode}"
export AUTONOMOUS_RUN_PROFILE="${AUTONOMOUS_RUN_PROFILE:-ELEVEN_OUT_OF_TEN_MODE}"
export AUTONOMOUS_RUN_DIR="${AUTONOMOUS_RUN_DIR:-runs/kraken_eleven_out_of_ten_mode}"

export AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S="${AUTONOMOUS_TRADES_SYNC_MIN_INTERVAL_S:-60}"
export AUTONOMOUS_KRAKEN_BALANCE_TTL_S="${AUTONOMOUS_KRAKEN_BALANCE_TTL_S:-30}"
export AUTONOMOUS_KRAKEN_TRADES_TTL_S="${AUTONOMOUS_KRAKEN_TRADES_TTL_S:-45}"
export AUTONOMOUS_CONFIDENCE_THRESHOLD="${AUTONOMOUS_CONFIDENCE_THRESHOLD:-0.44}"
export AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS="${AUTONOMOUS_LIQUIDITY_NIGHT_EDGE_ADD_BPS:-1.5}"
export AUTONOMOUS_ORDER_CADENCE_S="${AUTONOMOUS_ORDER_CADENCE_S:-9}"
export AUTONOMOUS_RISK_PER_TRADE="${AUTONOMOUS_RISK_PER_TRADE:-0.0025}"
export AUTONOMOUS_MAX_PORTFOLIO_HEAT_RATIO="${AUTONOMOUS_MAX_PORTFOLIO_HEAT_RATIO:-0.0125}"

exec "${ULTRA_SCRIPT}"
