from __future__ import annotations

import json
from pathlib import Path

import streamlit as st


def _read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        out = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return out if isinstance(out, dict) else {}


def _read_audit(path: Path, n: int = 100) -> list[dict]:
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines()[-n:]:
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except Exception:
            continue
        if isinstance(row, dict):
            rows.append(row)
    return rows


def _top_reasons(rows: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        payload = row.get("payload", {})
        if not isinstance(payload, dict):
            continue
        reason = str(payload.get("reason", "") or "").strip()
        if not reason:
            continue
        counts[reason] = counts.get(reason, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: kv[1], reverse=True)[:20])


def _write_overrides(path: Path, overrides: dict[str, str]) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "# Operator overrides generated by Streamlit UI",
    ]
    for k, v in sorted(overrides.items()):
        vv = str(v).replace('"', '\\"')
        lines.append(f'export {k}="{vv}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


st.set_page_config(page_title="Autonomous Trading Operator", layout="wide")
st.title("Autonomous Trading Operator UI")

run_dir_input = st.text_input("Run directory", value="runs/kraken_spot_live")
run_dir = Path(run_dir_input).expanduser()
dashboard_path = run_dir / "dashboard_snapshot.json"
audit_path = run_dir / "audit.log"
operator_path = run_dir / "operator_overrides.sh"

dashboard = _read_json(dashboard_path)
groups = dashboard.get("groups", {}) if isinstance(dashboard.get("groups"), dict) else {}
audit_rows = _read_audit(audit_path, n=100)
filtered_rows = [r for r in audit_rows if str(r.get("event_type", "")) in {"live_exec", "execution_submitted", "execution_report", "risk_reject", "governance_reject", "alert"}]

col1, col2, col3 = st.columns(3)
with col1:
    st.subheader("Execution")
    st.json(groups.get("execution", {}))
with col2:
    st.subheader("Efficiency")
    st.json(groups.get("efficiency", {}))
with col3:
    st.subheader("Microstructure")
    st.json(groups.get("microstructure", {}))

st.subheader("Top Block Reasons")
st.json(_top_reasons(audit_rows))

st.subheader("Operator Overrides")
pause_entries = st.checkbox("Pause New Entries (exits remain allowed)", value=False)
universe_override = st.text_input("Universe override (comma separated symbols)", value="")
max_orders = st.number_input("max_orders_per_min", min_value=1, max_value=200, value=12, step=1)
min_edge = st.number_input("min_net_edge_bps", min_value=0.1, max_value=10.0, value=1.0, step=0.1)
max_cost_alpha = st.number_input("max_cost_to_alpha_ratio", min_value=0.1, max_value=10.0, value=1.2, step=0.1)
growth_fraction = st.number_input("growth_max_fraction", min_value=0.05, max_value=1.0, value=0.5, step=0.05)

if st.button("Write operator_overrides.sh"):
    run_dir.mkdir(parents=True, exist_ok=True)
    overrides = {
        "AUTONOMOUS_OPERATOR_PAUSE_ENTRIES": "true" if pause_entries else "false",
        "AUTONOMOUS_MAX_ORDERS_PER_MIN": str(int(max_orders)),
        "AUTONOMOUS_MIN_NET_EDGE_BPS": f"{float(min_edge):.6g}",
        "AUTONOMOUS_MAX_COST_TO_ALPHA_RATIO": f"{float(max_cost_alpha):.6g}",
        "AUTONOMOUS_GROWTH_MAX_FRACTION": f"{float(growth_fraction):.6g}",
    }
    if universe_override.strip():
        overrides["AUTONOMOUS_OPERATOR_UNIVERSE_OVERRIDE"] = ",".join(
            [s.strip().upper() for s in universe_override.split(",") if s.strip()]
        )
    _write_overrides(operator_path, overrides)
    st.success(f"Wrote {operator_path}")

st.subheader("Recent Audit Events")
st.dataframe(filtered_rows, use_container_width=True)
