import type {
  AlertRecord,
  BrainState,
  DecisionRecord,
  ExecutionState,
  HealthState,
  IntegrityState,
  ReplayForensicsState,
  RuntimeControlAction,
  RuntimeControlResponse,
  RuntimeSummary,
  ShieldState,
  SymbolSnapshot,
  IncidentNoteInput,
  IncidentNoteResponse,
} from "@/types/runtime";

const now = "2026-03-29T16:42:00.000Z";

export const mockRuntimeSummary: RuntimeSummary = {
  providerId: "kraken_spot",
  mode: "tiny_live",
  runId: "run_20260329_1642_kraken_spot_tiny_live",
  runSelection: {
    mode: "latest",
    target: "runs/latest",
    resolvedRunDir: "/mock/runs/run_20260329_1642_kraken_spot_tiny_live",
  },
  runtimeIdentity: {
    runId: "run_20260329_1642_kraken_spot_tiny_live",
    runSelectionMode: "latest",
    runResolutionSource: "default_latest",
    runPath: "/mock/runs/run_20260329_1642_kraken_spot_tiny_live",
    providerId: "kraken_spot",
    mode: "tiny_live",
    stateKind: "degraded",
    reasonCode: "artifact_fallback_active",
    driftStatus: "tracking_latest",
    artifactFreshness: {
      status: "fresh",
      ageSeconds: 6,
      thresholdSeconds: 300,
      lastArtifactUpdateAt: now,
    },
    startedAt: "2026-03-29T12:12:00.000Z",
    lastArtifactUpdateAt: now,
    pinIntegrityStatus: "not_pinned",
    schemaVersion: 1,
  },
  startedAt: "2026-03-29T12:12:00.000Z",
  uptimeSec: 16200,
  portfolio: {
    equityEur: 12436.52,
    freeCashEur: 10873.2,
    openPositions: 2,
    openOrders: 3,
  },
  bridge: {
    avgLatencyMs: 83,
    wsConnected: true,
    restHealthy: true,
    health_status: "degraded",
    reasonCode: "artifact_fallback_active",
    reasonText: "Runtime API is not configured in this repo, UI is running against typed mock contracts.",
    lastUpdatedAt: now,
  },
  performance: {
    capitalUtilizationPct: 38.5,
    netExpectancyBps: 18.2,
    fillRate: 0.41,
    makerRatio: 0.73,
    targetGap: {
      net_bps_per_trade_gap: 11.8,
      capital_utilization_gap: 21.5,
    },
  },
};

export const mockSymbols: SymbolSnapshot[] = [
  {
    symbol: "BTC/EUR",
    venue: "Kraken SPOT",
    bid: 81234.5,
    ask: 81260.4,
    spreadBps: 3.2,
    latencyMs: 79,
    qualityScore: 0.97,
    stale: false,
    ts: now,
  },
  {
    symbol: "ETH/EUR",
    venue: "Kraken SPOT",
    bid: 4234.2,
    ask: 4237.8,
    spreadBps: 8.5,
    latencyMs: 87,
    qualityScore: 0.92,
    stale: false,
    ts: now,
  },
  {
    symbol: "SOL/EUR",
    venue: "Kraken SPOT",
    bid: 171.16,
    ask: 171.44,
    spreadBps: 16.4,
    latencyMs: 141,
    qualityScore: 0.71,
    stale: true,
    ts: "2026-03-29T16:35:42.000Z",
  },
];

export const mockDecisions: DecisionRecord[] = [
  {
    id: "dec_01",
    symbol: "BTC/EUR",
    ts: now,
    intent: "probe_long",
    confidence: 0.68,
    expectedEdgeBps: 24,
    blockers: [],
    topReasons: [
      "Doctrine survival score remains above live threshold.",
      "Market integrity is degraded but not blocked.",
    ],
    riskVerdict: "watch",
    lastAction: "size_cut_0.35x",
  },
  {
    id: "dec_02",
    symbol: "SOL/EUR",
    ts: now,
    intent: "wait",
    confidence: 0.34,
    expectedEdgeBps: -8,
    blockers: ["stale_market_data", "thin_book_depth"],
    topReasons: [
      "Latency and quality scores fell below configured operator comfort.",
      "Counterfactual wait value dominates immediate entry.",
    ],
    riskVerdict: "block",
    lastAction: "no_trade",
  },
];

export const mockAlerts: AlertRecord[] = [
  {
    id: "alert_01",
    severity: "critical",
    module: "market_integrity_service",
    message: "SOL/EUR feed freshness breached operator threshold; new opens blocked on affected symbol.",
    ts: now,
  },
  {
    id: "alert_02",
    severity: "warn",
    module: "runtime_bridge",
    message: "UI is consuming local mock runtime contracts until NEXT_PUBLIC_RUNTIME_API_URL is configured.",
    ts: now,
  },
];

export const mockHealth: HealthState = {
  status: "warn",
  bridgeHealthy: true,
  backendHealthy: false,
  artifactFallbackActive: true,
  lastUpdatedAt: now,
  warnings: [
    "Runtime backend URL is not configured.",
    "Artifact fallback is active for operator visibility only.",
  ],
  details: [
    { label: "Bridge", value: "typed mock adapter", severity: "info" },
    { label: "Backend", value: "unconfigured", severity: "warn" },
    { label: "Artifact fallback", value: "active", severity: "warn" },
  ],
  runtimeIdentity: mockRuntimeSummary.runtimeIdentity,
};

export const mockIntegrity: IntegrityState = {
  doctrineStatus: "guarded",
  capabilityConfidence: "partial",
  blockers: ["runtime_api_missing", "release_signing_inputs_missing"],
  unlockActions: [
    "Provide NEXT_PUBLIC_RUNTIME_API_URL and backend /runtime/* endpoints.",
    "Provide real operator auth provider or token exchange.",
    "Provide Apple signing and notarization credentials before claiming release readiness.",
  ],
  warnings: [
    "This shell is runnable and typed, but it is not connected to canonical runtime truth yet.",
    "macOS release remains blocked on external signing inputs.",
  ],
  degradationState: "partial",
  details: [
    { label: "Runtime source of truth", value: "missing backend endpoint", severity: "warn" },
    { label: "Auth provenance", value: "local persisted session only", severity: "warn" },
    { label: "Release workflow", value: "scripted but awaiting secrets", severity: "info" },
  ],
  lastUpdatedAt: now,
  stateKind: "partial",
  runtimeIdentity: {
    ...mockRuntimeSummary.runtimeIdentity,
    stateKind: "partial",
    reasonCode: "runtime_api_missing",
  },
};

export const mockReplay: ReplayForensicsState = {
  runId: mockRuntimeSummary.runId,
  stateKind: "partial",
  lastUpdatedAt: now,
  timeline: [
    {
      label: "Open",
      detail: "BTC/EUR probe opened at 0.35x normal size due doctrine risk throttle.",
      ts: "2026-03-29T14:10:03.000Z",
      severity: "info",
    },
    {
      label: "Integrity degradation",
      detail: "SOL/EUR freshness slipped; venue monitor escalated symbol block without global flatten.",
      ts: "2026-03-29T15:24:11.000Z",
      severity: "warn",
    },
  ],
  incidents: [
    {
      label: "SEV-2 candidate",
      detail: "Market data freshness degraded on non-primary symbol. Manual review required before resume on affected symbol.",
      ts: "2026-03-29T15:24:11.000Z",
      severity: "warn",
    },
  ],
  analogMatches: [
    {
      label: "Analog 2026-03-18",
      detail: "Similar freshness gap resolved by venue reconnect; no flatten required after symbol quarantine.",
      ts: "2026-03-18T11:04:00.000Z",
      severity: "info",
    },
  ],
  counterfactuals: [
    {
      label: "Wait vs trade now",
      detail: "Waiting on SOL/EUR avoided estimated -11 bps adverse excursion in analogous book conditions.",
      ts: now,
      severity: "good",
    },
  ],
  pnlAttribution: [
    {
      label: "BTC/EUR probe",
      detail: "+43.12 EUR realized; 71% from favorable drift, 29% from spread capture.",
      ts: now,
      severity: "good",
    },
  ],
  notes: [
    {
      label: "Operator note template",
      detail: "Confirm root cause, verify audit reference, then create replay review task.",
      ts: now,
      severity: "info",
    },
  ],
  runtimeIdentity: {
    ...mockRuntimeSummary.runtimeIdentity,
    stateKind: "partial",
    reasonCode: "runtime_api_missing",
  },
};

export const mockBrain: BrainState = {
  runId: mockRuntimeSummary.runId,
  selectedSymbol: "BTC/EUR",
  actionState: "trade_smaller",
  whyTrade: [
    "Forecast edge remains positive after doctrine scaling.",
    "Market integrity is degraded but still in continue state.",
  ],
  whyNotTrade: [
    "Lifecycle confidence remains partial.",
    "User stream evidence is not yet strong enough for full sizing.",
  ],
  blockingReasons: ["user_stream_confidence_partial", "lifecycle_partial"],
  supportingSignals: ["spread_health", "market_quality", "bounded_support"],
  costAdjustedEdgeBps: 16.87,
  costAdjustedEdgeSource: "operator_summary.decision.execution_plan.reasons.components[0].net_after_cost_bps",
  sellFloorStatus: "min_net_profit_bps=120 net_profit_sell_block=True",
  marketRegime: "RANGE",
  riskGatingOutcome: "continue",
  executionEligibilityOutcome: "trade_smaller",
  pipeline: [
    {
      id: "market_ingest",
      title: "Market ingest",
      status: "pass",
      reasonCodes: [],
      latencyMs: 79,
      timestamp: now,
      inputSummary: "provider=kraken_spot universe=3 symbols",
      outputSummary: "live public quote snapshots loaded",
      evidence: ["config_manifest.json", "market_integrity_journal.jsonl"],
      derived: false,
    },
    {
      id: "risk_gating",
      title: "Risk gating",
      status: "warn",
      reasonCodes: ["user_stream_confidence_partial", "lifecycle_partial"],
      latencyMs: null,
      timestamp: now,
      inputSummary: "market_integrity + doctrine",
      outputSummary: "action=continue confidence=partial score=0.75",
      evidence: ["market_integrity_journal.jsonl", "decision_explainability.json"],
      derived: false,
    },
    {
      id: "execution_eligibility",
      title: "Execution eligibility",
      status: "warn",
      reasonCodes: ["trade_smaller"],
      latencyMs: null,
      timestamp: now,
      inputSummary: "execution plan + lifecycle proof",
      outputSummary: "trade_smaller with bounded lifecycle proof",
      evidence: ["kraken_spot_operator_summary.jsonl"],
      derived: false,
    },
  ],
  symbolViews: [
    {
      symbol: "BTC/EUR",
      venue: "Kraken SPOT",
      bid: 81234.5,
      ask: 81260.4,
      spreadBps: 3.2,
      depthNotional: 316602.72,
      signal: "bounded_support",
      forecast: "RANGE",
      confidence: 0.81,
      currentBlockReason: "user_stream_confidence_partial",
      lastAction: "CONTINUE",
      nextEligibleAction: "trade_smaller",
      derivedFields: ["nextEligibleAction derived from decision intent plus live ordering gate"],
      ts: now,
    },
    {
      symbol: "SOL/EUR",
      venue: "Kraken SPOT",
      bid: 171.16,
      ask: 171.44,
      spreadBps: 16.4,
      depthNotional: null,
      signal: "wait_dominates",
      forecast: "RANGE",
      confidence: 0.34,
      currentBlockReason: "thin_book_depth",
      lastAction: "WAIT",
      nextEligibleAction: "blocked",
      derivedFields: ["nextEligibleAction derived from live ordering gate"],
      ts: "2026-03-29T16:35:42.000Z",
    },
  ],
  decisionReplay: {
    finalVerdict: "trade_smaller",
    timeline: mockReplay.timeline,
    evidence: [...mockReplay.incidents, ...mockReplay.notes],
    linkedArtifacts: [
      "decision_explainability.json",
      "kraken_spot_operator_summary.jsonl",
      "market_integrity_journal.jsonl",
    ],
  },
  opportunityRanking: {
    selectedPlaybook: "trend_follow_entry",
    selectedScore: 0.82,
    backlogPressure: 0.44,
    falseNegativeRate: 0.08,
    falsePositiveRate: 0.11,
    topCandidates: [
      {
        symbol: "BTC/EUR",
        playbook: "trend_follow_entry",
        score: 0.82,
        netEdgeBps: 24,
        qualityOfEdge: 0.79,
        executionPreference: "maker_first",
      },
      {
        symbol: "ETH/EUR",
        playbook: "pullback_reentry",
        score: 0.66,
        netEdgeBps: 17,
        qualityOfEdge: 0.63,
        executionPreference: "maker_first",
      },
    ],
  },
  evidenceNotes: [
    "costAdjustedEdgeBps is only shown when a direct net-after-cost field exists.",
    "nextEligibleAction is marked derived when inferred from the current gate posture.",
  ],
  stateKind: "partial",
  lastUpdatedAt: now,
  runtimeIdentity: mockIntegrity.runtimeIdentity,
};

export const mockShield: ShieldState = {
  runId: mockRuntimeSummary.runId,
  trustVerdict: "caution",
  trustReasons: ["runtime_state:partial", "safety_ready:false", "runtime_tracking_latest"],
  runtimeSafety: [
    {
      label: "Runtime identity",
      status: "caution",
      detail: "selection=latest drift=tracking_latest",
      evidence: ["runtimeIdentity.runSelectionMode", "runtimeIdentity.driftStatus"],
      ts: now,
    },
    {
      label: "Execution gate",
      status: "caution",
      detail: "preflight_ok=true rollout_stage=tiny_live",
      evidence: ["live_safety_summary.json"],
      ts: now,
    },
    {
      label: "Market integrity",
      status: "caution",
      detail: "action=continue confidence=partial score=0.75",
      evidence: ["market_integrity_journal.jsonl"],
      ts: now,
    },
  ],
  appliedControl: {
    action: "force_degraded",
    controlSurface: "meta_governor",
    mode: "live",
    degradationApplied: true,
    forcedRiskMode: "degraded",
    sizeMultiplier: 0.05,
    reasons: ["user_stream_confidence_partial", "lifecycle_partial"],
    flattenedStatus: null,
    killPath: null,
    steps: 8,
    ts: now,
  },
  queuedCommand: {
    action: "freeze",
    reasonCode: "operator_freeze",
    reasonText: "manual review before resume",
    operatorId: "ops.mh",
    effectiveState: "awaiting_runtime_ack",
    auditReference: "audit-freeze-01",
    ts: now,
  },
  userStream: {
    status: "partial",
    detail: "token acquired, socket open, channels=openOrders,ownTrades",
    subscribedChannels: ["openOrders", "ownTrades"],
    lastEventType: "subscribe",
    lastEventAt: now,
    evidence: ["events_user_stream.jsonl", "user_stream_audit.jsonl"],
  },
  guardMatrix: [
    {
      name: "Max exposure",
      configuredThreshold: "35",
      observedValue: "12",
      status: "ok",
      impact: "Blocks new entries when gross exposure exceeds rollout envelope.",
      evidence: ["events_account.jsonl", "rollout_profile.max_exposure_notional"],
      lastTriggeredAt: null,
      derived: false,
    },
    {
      name: "Spread guard",
      configuredThreshold: "12",
      observedValue: "3.2",
      status: "ok",
      impact: "Blocks entry when spread exceeds rollout threshold.",
      evidence: ["market_integrity_journal.jsonl"],
      lastTriggeredAt: null,
      derived: false,
    },
    {
      name: "Execution throttle",
      configuredThreshold: "2 orders/min",
      observedValue: "unavailable",
      status: "unavailable",
      impact: "Per-minute throttle is not emitted in mock mode.",
      evidence: ["rollout_profile.max_orders_per_min"],
      lastTriggeredAt: null,
      derived: false,
    },
  ],
  performanceControl: {
    promotionScore: 0.58,
    rollbackTriggered: false,
    recoveryMode: "watchful_normal",
    privateStreamHealth: "connected",
  },
  truthNotes: [
    "Pinned mode never silently falls back to latest; mock mode keeps tracking_latest explicit.",
    "Guard comparisons only happen where both threshold and observation exist.",
  ],
  linkedArtifacts: ["live_safety_summary.json", "market_integrity_journal.jsonl"],
  stateKind: "partial",
  lastUpdatedAt: now,
  runtimeIdentity: mockIntegrity.runtimeIdentity,
};

export const mockExecution: ExecutionState = {
  runId: mockRuntimeSummary.runId,
  summary: [
    {
      label: "Orders submitted",
      value: 3,
      unit: "count",
      detail: "Direct from mock execution health.",
      derived: false,
    },
    {
      label: "Fill rate",
      value: 66.67,
      unit: "percent",
      detail: "Derived as fills / orders_submitted * 100.",
      derived: true,
    },
    {
      label: "Order-to-fill latency",
      value: 145,
      unit: "ms",
      detail: "Derived from fill payload latency samples.",
      derived: true,
    },
  ],
  orders: [
    {
      id: "ord-001",
      symbol: "BTC/EUR",
      side: "buy",
      quantity: null,
      targetNotional: 12,
      price: 81248.1,
      fees: 0.08,
      slippage: 0.03,
      status: "partially filled",
      venueResponseSummary: "kraken_spot:intent_submitted",
      rejectionReason: null,
      decisionTs: "2026-03-29T16:38:00.000Z",
      submittedTs: "2026-03-29T16:38:01.000Z",
      acknowledgedTs: "2026-03-29T16:38:01.150Z",
      filledTs: "2026-03-29T16:38:02.000Z",
      canceledTs: null,
      rejectedTs: null,
      transitions: [
        { label: "Order Intent", detail: "target_notional=12", ts: "2026-03-29T16:38:00.000Z", severity: "info" },
        { label: "Order Lifecycle Transition", detail: "to_state=submitted", ts: "2026-03-29T16:38:01.000Z", severity: "info" },
        { label: "Fill", detail: "status=filled_partial_maker", ts: "2026-03-29T16:38:02.000Z", severity: "good" },
      ],
      derivedFields: ["quantity unavailable; targetNotional retained from order intent"],
    },
    {
      id: "ord-002",
      symbol: "SOL/EUR",
      side: "buy",
      quantity: null,
      targetNotional: 10,
      price: null,
      fees: null,
      slippage: null,
      status: "rejected",
      venueResponseSummary: "runtime:order_rejected",
      rejectionReason: "Insufficient funds",
      decisionTs: "2026-03-29T16:39:00.000Z",
      submittedTs: "2026-03-29T16:39:01.000Z",
      acknowledgedTs: null,
      filledTs: null,
      canceledTs: null,
      rejectedTs: "2026-03-29T16:39:01.400Z",
      transitions: [
        { label: "Order Intent", detail: "target_notional=10", ts: "2026-03-29T16:39:00.000Z", severity: "info" },
        { label: "Order Lifecycle Transition", detail: "to_state=rejected", ts: "2026-03-29T16:39:01.400Z", severity: "warn" },
      ],
      derivedFields: [],
    },
  ],
  positions: [
    {
      symbol: "BTC/EUR",
      side: "long",
      quantity: null,
      exposureNotional: 12,
      entryPrice: 81248.1,
      markPrice: 81260.4,
      unrealizedPnl: 0.18,
      realizedPnl: 43.12,
      costBasis: 81248.1,
      holdDurationSec: 420,
      exitEligibility: "reduce_only",
      sellFloorStatus: "min_net_profit_bps=120",
      derivedFields: ["exposureNotional derived from latest position/account snapshot"],
      ts: now,
    },
  ],
  accountSnapshot: {
    venue: "kraken_spot",
    symbol: "BTC/EUR",
    baselineBalance: 12436.52,
    exchangeBalance: 12435.91,
    grossExposureNotional: 12,
    localCashDelta: -12,
    realizedPnl: 43.12,
    unrealizedPnl: 8.34,
    cumulativeFees: 0.08,
    cumulativeSlippage: 0.03,
    fillCount: 2,
    ts: now,
    derivedFields: ["Account snapshot is direct from mock events_account.jsonl."],
  },
  venueTelemetry: {
    userStreamStatus: "partial",
    lastUserStreamEvent: "subscribe",
    subscribedChannels: ["openOrders", "ownTrades"],
    lifecycleStatus: "rejected",
    lifecycleUpgradeEligible: false,
    lifecycleGapReasons: [],
    lastLifecycleReason: "order_rejected",
    reconciliationStatus: "partial_without_snapshot",
    executionPlanStyle: "passive_limit",
    fillProbability: 0.98,
    ts: now,
    evidence: [
      "events_user_stream.jsonl",
      "user_stream_audit.jsonl",
      "lifecycle_evidence_journal.jsonl",
      "execution_journal.jsonl",
    ],
  },
  alphaTelemetry: {
    privateStreamHealth: { status: "connected", heartbeatAgeSeconds: 2 },
    orderRejectTaxonomy: { topReject: "post_only_would_take", rejectRate: 0.03 },
    makerFirstEffectiveness: { makerProbability: 0.73, captureRate: 0.61 },
    executionQualityBucket: { quality_bucket: "medium", quality_of_edge: 0.68 },
    entryTimingOptimizer: { recommended_entry_style: "maker_first", opportunity_decay: 0.21 },
    adaptiveCadence: { recommended_cadence_s: 6.2, backlog_pressure: 0.44 },
    liveDegradation: { status: "stable", live_degradation_score: 0.12 },
    selfThrottling: { active: false, aggressiveness_scalar: 0.92 },
  },
  timeline: [
    { label: "Decision emitted", detail: "BTC/EUR trade_smaller", ts: "2026-03-29T16:38:00.000Z", severity: "info" },
    { label: "Risk approved", detail: "market_integrity continue", ts: "2026-03-29T16:38:00.200Z", severity: "info" },
    { label: "Fill", detail: "partial maker fill recorded", ts: "2026-03-29T16:38:02.000Z", severity: "good" },
  ],
  dataNotes: [
    "Orders surface only uses direct order/fill lifecycle artifacts.",
    "Position rows are emitted only when current exposure is observable.",
  ],
  linkedArtifacts: ["events_orders.jsonl", "events_fills.jsonl", "events_account.jsonl"],
  stateKind: "partial",
  lastUpdatedAt: now,
  runtimeIdentity: mockIntegrity.runtimeIdentity,
};

export function buildMockControlResponse(
  action: RuntimeControlAction,
  operatorId: string | undefined,
): RuntimeControlResponse {
  return {
    accepted: true,
    rejected: false,
    status: "acknowledged",
    operatorMessage: `Mock ${action} accepted. Replace mock adapter with POST /runtime/control/${action} to make this authoritative.`,
    auditReference: `mock-audit-${action}-20260329-1642`,
    effectiveState: action === "resume" ? "resuming" : action === "pause" ? "paused" : action,
    operatorId,
    ts: now,
  };
}

export function buildMockIncidentResponse(payload: IncidentNoteInput): IncidentNoteResponse {
  return {
    accepted: true,
    noteId: `mock-note-${payload.runId}`,
    auditReference: `mock-incident-${payload.runId}`,
    operatorMessage: "Mock incident note stored locally in UI memory contract. Wire POST /runtime/incident-note for audit truth.",
    ts: now,
  };
}
